### ISSUE TITLE
onState中的回调执行时间, 有时会比dispatch执行的函数更快

### ISSUE THREAD

**Issue by democheng-cz** [coderwhy/hy-event-store#14]
`getRankMenuDetail(ctx,payload){
      getSongMenuDetail(payload).then(res=>{
        ctx.rankSongMenu = res.playlist
        console.log(res.playlist)
      })
    }`

`recommendStore.onState("rankSongMenu",(res)=>{
      this.setData({showData:res})
    })`

执行顺序正常是先执行第一个,然后是第二个, 但是当我多次点击的时候, 他们的执行顺序发生了变化

**Comment by coderwhy** [comment]
onState的使用需要绑定一次，不需要进行多次绑定（比如放到onLoad中，不需要放到点击事件的回调中）。
onState会在第一次绑定执行一次，后面dispatch改变的时候就会再次执行了
