### ISSUE TITLE
此处的keys没有定义

### ISSUE THREAD

**Issue by CanwDaniel** [coderwhy/hy-event-store#4]
![image](https://user-images.githubusercontent.com/29409114/150499418-837587ba-8dcd-4e3b-9ada-08be75794c46.png)

**Comment by coderwhy** [comment]
好的，源码已经修复，马上会更新到npm上面

**Comment by CanwDaniel** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
