### ISSUE TITLE
导入HYEventStore 报错 module "store/hy-event-store.js" is not defined

### ISSUE THREAD

**Issue by zanxiaoyu** [coderwhy/hy-event-store#6]

**Comment by qq229338869** [comment]
如果是微信小程序，开发者工具->工具->构建npm

**Comment by 317085** [comment]
使用了微信小程序里面的构建npm，也会出现这个问题，解决方案：版本使用稳定点的就行了

![image](https://user-images.githubusercontent.com/76804301/165725436-5c135284-a258-437d-9e6d-facd70ddd986.png)

**Comment by Gxyloj** [comment]
上面两种方式都无效，还是提示Error: module "store/hy-event-store.js" is not defined
还有没有什么办法啊

**Comment by haiboume** [comment]
> 上面两种方式都无效，还是提示Error: module "store/hy-event-store.js" is not defined 还有没有什么办法啊

直接把源代码放项目目录里面，直接引用，不要从node_modules引用

**Comment by rb05180518** [comment]
安装时使用npm install hy-event-store@1.1.0即可

**Comment by coderwhy** [comment]
后续的版本中已经修复这个问题了
